config/routes.rb
Rails.application.routes.draw do
  

  get "/auth/:provider/callback", to: "sessions#create_github"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  delete 'logout' => 'sessions#destroy'


  get 'users/new'
  get 'users/create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'auth/github', as: 'github_auth'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/users', to: "users#index"

  # #index
  # get '/landscapes', to: "landscapes#index"

  # #new
  # get '/landscapes/new', to: "landscapes#new"

  # #show
  # get '/landscapes/:id', to: "landscapes#show", as: "landscape"

  # #create
  # post '/landscapes', to: "landscapes#create", as: "create_landscape"

  # #edit
  # get '/landscapes/:id/edit', to: "landscapes#edit", as: "edit_landscape"

  # #update
  # patch '/landscapes/:id', to: "landscapes#update"

  # #destroy
  # delete '/landscapes/:id', to: "landscapes#destroy"

  #  #index
  #  get '/teams', to: "teams#index"

  #  #new
  #  get '/teams/new', to: "teams#new"
 
  #  #show
  #  get '/teams/:id', to: "teams#show", as: "team"
 
  #  #create
  #  post '/teams', to: "teams#create", as: "create_teams"
 
  #  #edit
  #  get '/teams/:id/edit', to: "teams#edit", as: "edit_teams"
 
  #  #update
  #  patch '/teams/:id', to: "teams#update"
 
  #  #destroy
  #  delete '/teams/:id', to: "teams#destroy"

  #log_in
  resources :users, only: [:new, :create, :edit, :update, :destroy, :show]
 

  # root to: "application#welcome"

 
  # match "/auth/:provider/callback" => "sessions#create_github", :via => [:get, :post]
  resources :sessions


  resources :teams do 
    resources :landscapes, only: [:index, :show, :new, :create]
  end

  get '/landscapes/search', to:"landscapes#search",  as: "search_landscapes"
  get '/search', to:"landscapes#resolved"
  
  resources :landscapes




  get '/', to: "application#welcome"
  get '/:anything', to: "application#wrong_page"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :landscapes
    has_many :teams, :through => :landscapes
    validates :email, uniqueness: true
    validates :email, presence: true
    accepts_nested_attributes_for :landscapes, reject_if: proc { |attributes| attributes['address'].blank?} 

    # def self.create_with_omniauth(auth)
    #     byebug
    #     create! do |user|
    #       user.provider = auth["provider"]
    #       user.name = auth["info"]["name"]
    #       user.email = auth["info"]["email"]
    #       user.password = auth['credentials']['token']

    #     end
    #     user
    # end

    def self.find_or_create_by_auth(auth)
  
        user = User.find_or_create_by(provider: auth['provider'])
    
       
        user.name = auth['info']['name']
        user.email = auth['info']['email']
        user.password = auth['credentials']['token']
    
        user.save
        user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]
  def new
    @user = User.new
    3.times { @user.landscapes.build }
    
  end

  def new_github
  end

 
  def create
    
    @user = User.new(user_params)
    
    if @user.save
        
        flash[:notice] = "Created successfully!"
        session[:user_id] = @user.id
        redirect_to '/welcome'
    else
        flash[:error] = @user.errors.full_messages
        redirect_to users_new_path
        # render "new"
    end
 end

 def show 
    if check_user_using_userID
        @user = find_user_byID
        
        if @user
            render "show"
        else
            redirect_to user_path(current_user.id)
        end
    else
        redirect_to user_path(current_user.id)
    end
   
end

 def edit
    if check_user_using_userID
        @user = find_user_byID
        
        if @user
            render 'edit'
        else
            redirect_to user_path(current_user.id)
        end
    else
        redirect_to user_path(current_user.id)
    end
   

end

def update

    
    @user =  find_user_byID

    if @user
        @user.update(user_params)
        if @user.errors.any?
            render "edit"
        else
            redirect_to @user
        end
    else
        render "edit"
    end
  
end

def destroy
    if check_user_using_userID
        @user = find_user_byID
        @user.landscapes.each do |l|
            l.user_id = nil
        end
        @user.destroy
        redirect_to users_path
    else
        redirect_to user_path(current_user.id)
    end
end

    private


    def find_user_byID
        @user2 = User.find_by(id:params[:id])
        @user2
    end


    def user_params
        params.require(:user).permit(:name, :email,:password, :password_digest, :id, :team_id, landscapes_attributes:[:id, :address, :area, :team_id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Change User Info</h1>

<%= form_with model:@user do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %><br>
    <%= form.label :password %>
    <%= form.password_field :password %><br>
    <h4>Landscape</h4>
    <%# <%= form.fields_for :landscapes do |land| %>

    <%= form.fields_for :landscapes do |l| %>
        <%= l.label "Address"%>
        <%= l.text_field :address %>
        <%= l.label "Area (square feet)" %>
        <%= l.number_field :area%>
        <%= l.label "Team" %>
        <%= l.number_field :team_id %> <br>
    <% end %>



 
  
    <%= form.submit "Submit" %>

<%end %>

app/views/users/login.erb
<h1> Log in </h1>

<form action="/login" method="post">
    <input type="text" placeholder="email" name="email">
    <input type="password" placeholder="password" name="password">
    <input type="submit" name="Log in">

</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with model:@user, local: :true do |f| %>
  <%= f.label :email%><br>
  <%= f.text_field :email, class: @user.errors.any? ? "error-field" : nil %><br>
  <%= f.label :name%><br>
  <%= f.text_field :name%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <h4>Landscape</h4>
    <%= f.fields_for :landscapes do |land| %>
        <%= land.label :address %>
        <%= land.text_field :address %>
        <%= land.label "Area (square feet)" %>
        <%= land.number_field :area %>
        <%= land.label :team_id %>
        <%= land.number_field :team_id %> <br>
    <% end %>
  <%= f.submit %>
<%end%>

    



    

app/views/users/show.html.erb
<h1>User Profile </h1>
<ul>
    <h5>ID: <%= @user.id %></h4>
    <h5>Name: <%= @user.name %></h4>
    <h5>Email: <%= @user.email %></h4>

    <h4>Landscapes:</h4>
    <ul>
        <% @user.landscapes.each do |l| %>
            <li>
            <%= link_to l.address, landscape_path(l) %> - Team: 
            <% if l.team_id  %>
                <%= link_to l.team_id, team_path(l.team_id) %>
            <% else %>
                Does not have any workers in this team!
            <% end %>
            </li>
        <% end %>
    </ul>
    


</ul>
<h6><%= link_to("Edit", edit_user_path(@user)) %></h6>
<h6><%= link_to("Delete", @user, method: :delete, data:{confirm: "Are you sure?"}) %></h6>