config/routes.rb
Rails.application.routes.draw do
  

  get "/auth/:provider/callback", to: "sessions#create_github"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  delete 'logout' => 'sessions#destroy'


  get 'users/new'
  get 'users/create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'auth/github', as: 'github_auth'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/users', to: "users#index"

  # #index
  # get '/landscapes', to: "landscapes#index"

  # #new
  # get '/landscapes/new', to: "landscapes#new"

  # #show
  # get '/landscapes/:id', to: "landscapes#show", as: "landscape"

  # #create
  # post '/landscapes', to: "landscapes#create", as: "create_landscape"

  # #edit
  # get '/landscapes/:id/edit', to: "landscapes#edit", as: "edit_landscape"

  # #update
  # patch '/landscapes/:id', to: "landscapes#update"

  # #destroy
  # delete '/landscapes/:id', to: "landscapes#destroy"

  #  #index
  #  get '/teams', to: "teams#index"

  #  #new
  #  get '/teams/new', to: "teams#new"
 
  #  #show
  #  get '/teams/:id', to: "teams#show", as: "team"
 
  #  #create
  #  post '/teams', to: "teams#create", as: "create_teams"
 
  #  #edit
  #  get '/teams/:id/edit', to: "teams#edit", as: "edit_teams"
 
  #  #update
  #  patch '/teams/:id', to: "teams#update"
 
  #  #destroy
  #  delete '/teams/:id', to: "teams#destroy"

  #log_in
  resources :users, only: [:new, :create, :edit, :update, :destroy, :show]
 

  # root to: "application#welcome"

 
  # match "/auth/:provider/callback" => "sessions#create_github", :via => [:get, :post]
  resources :sessions


  resources :teams do 
    resources :landscapes, only: [:index, :show, :new, :create]
  end

  get '/landscapes/search', to:"landscapes#search",  as: "search_landscapes"
  get '/search', to:"landscapes#resolved"
  
  resources :landscapes




  get '/', to: "application#welcome"
  get '/:anything', to: "application#wrong_page"
end

app/models/landscape.rb
class Landscape < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :team, optional: true
    validates :address, uniqueness: true, presence: true
end

app/controllers/landscapes_controller.rb
class LandscapesController < ApplicationController

    
    def index 
        if params[:team_id]
            set_team
            @landscapes = @team.landscapes
        else
            @landscapes = Landscape.all
        end
    end



    def show 
        @landscape = find_landscape_byID
       
        if params[:team_id]
            set_team
        end 
    end

    def new 
        if params[:team_id]
            set_team
            @landscape = @team.landscapes.build
        else
            @landscape = Landscape.new
        end
        
    end

    def create
           
        if params[:team_id]
            set_team
            @landscape = @team.landscapes.build(landscape_params)
        else
            @landscape = Landscape.new(landscape_params)
        end

        if @landscape.save
            redirect_to @landscape
        else
            render "new"
        end
    end

    def edit
        
        if check_user_using_landscapeID
            
            @landscape = find_landscape_byID
            if @landscape
                render 'edit'
            else
                redirect_to landscapes_path
            end
        else
        
            redirect_to landscapes_path
        end
    end

    def update
        @landscape =  find_landscape_byID
        if @landscape
            @landscape.update(landscape_params)
            if @landscape.errors.any?
                render "edit"
            else
                redirect_to @landscape
            end
        else
            render "edit"
        end
      
    end

    def destroy
        if check_user_using_landscapeID
            @landscape = find_landscape_byID
            @landscape.destroy
            redirect_to landscapes_path
        else
            redirect_to landscapes_path
        end
    end

    def search
    end

    # Search for what matches the Query
    # recive query & display matches
    # get
    def resolved
    
        # @landscapes = Landscape.all.find_all
        @landscapes = Landscape.all.find_all{|s| s.address.downcase.include?(params[:query].downcase)}
        # @landscapes.each do |s|
           
        #     if s.address.downcase.include?(params[:query].downcase)
        #         @landscape << s.address.downcase.include?(params[:query].downcase)
        #     end
        # end
    end





    private

    def set_team
        @team = Team.find_by_id(params[:team_id])
    end

    def find_landscape_byID
        @landscape2 =  Landscape.find_by(id:params[:id])
        @landscape2
    end

    def landscape_params
        params.require(:landscape).permit(:address, :id, :team_id, :query,:user_id, :area, :team_id)
    end
end

app/helpers/landscapes_helper.rb
module LandscapesHelper
end

app/views/landscapes/edit.html.erb
<h1>Change Landscape Info</h1>

<%= form_with model:@landscape, id: :new_landscape do |form| %>
    <%= form.label :address %>
    <%= form.text_field :address %><br>
    <%= form.label "Area" %>
    <%= form.text_field :area %><br>
    <%= form.label "Team_id" %>
    <%= form.text_field :team_id %><br>
    <%= form.label "User_id" %>
    <%= form.text_field :user_id %><br>
    <%= form.submit "Submit" %>

<%end %>

app/views/landscapes/index.html.erb
<% if @team %>
<h2><%= @team.name %> Team's Landscapes</h2>
<% else %>
<h2>All Landscapes:</h2>
<% end %>
<ul>

<% if @team %>
    <% @landscapes.each do |land|  %>
        <li> <%= link_to land.address, team_landscape_path(@team, land) %></li>
        
    <% end %>
<% else %>
    <% @landscapes.each do |land|  %>

        <li><%= link_to land.address, landscape_path(land) %></li>
    <% end %>
<% end %>
<ul>

app/views/landscapes/new.html.erb
<h1>New Landscape</h1>

<% if @landscape.errors.any? %>
    <h5 style="color: red"><%= @landscape.errors.full_messages.to_sentence %></h5>
<% end %>
<br>
<%# form tag need a url or url_path_helper where it posts to %>
<%# if we use form_for then using Landscape.new and create a |form| instance in do-end loop, then use form.text_field %>
<%= form_with model: [@team, @landscape], local: :true do |form| %>
    <%= form.label "Address" %>
    <%= form.text_field :address, class: @landscape.errors.any? ? "error-field" : nil %><br>
    <%= form.label "Area" %>
    <%= form.text_field :area %><br>
    <%= form.label "Team_id" %>
    <%= form.text_field :team_id %><br>
    <%= form.label "User_id" %>
    <%= form.text_field :user_id %><br>
    <%= form.submit "Submit" %>

<%end %>

app/views/landscapes/resolved.html.erb
<ul>
    <% @landscapes.each do |l| %>
    <li> <%= link_to(l.address, l)%></li>
    <% end %>
</ul>

app/views/landscapes/search.html.erb
<%= form_with url:"/search", method: :get , local:true do |form| %>
<%= form.text_field :query %>
<%= form.submit "Search" %>
<% end %>

app/views/landscapes/show.html.erb
<% if @team %>
<h2><%= @team.name %> Team's Landscape:</h2>
<% else %>
    <h2>Landscape Info</h2>
<% end %>


<h4 class="red-text"> Address: <%= @landscape.address %></h4>
<h4 class="red-text"> Area (square feet): <%= @landscape.area %></h4>
<% if @landscape.user_id  %>
    <h4 class="red-text"> User_id: <%= @landscape.user_id %></h4>
<% end %>
<% if @landscape.team_id  %>
    <h4 class="red-text"> Team_id: <%= @landscape.team_id %></h4>
<% end %>


<% if check_user_using_landscapeID %>
    <h6><%= link_to("Edit", edit_landscape_path(@landscape)) %></h6>

    <h6><%= link_to("Delete", @landscape, method: :delete, data:{confirm: "Are you sure?"}) %></h6>
<% end %>